### ISSUE TITLE
XML lists

### ISSUE THREAD

**Issue by idgm81** [enen92/P2P-Streams-Kodi#74]
Hi enen92,

I'm using a xml list (based on livestream format) on my raspi but your addon doesn't recognize it correctly.

Once addon has loaded the list, then any link is shown like list was empty

My list is written like this one:

http://divingmules-repo.googlecode.com/svn/trunk/plugin.video.live.streams/items_example.xml

Thanks for your job

**Comment by enen92** [comment]
Probably some error in the format of the list..
That url works fine if you add it as a remote list.

**Comment by idgm81** [comment]
Added as remote list works but not as local, quite strange :(

**Comment by enen92** [comment]
humm might be an error with xbmcvfs, I'll check

**Comment by enen92** [comment]
I've checked it and the list is added and lists the items correctly.

run:

cd $HOME/pi
wget http://divingmules-repo.googlecode.com/svn/trunk/plugin.video.live.streams/items_example.xml

Add the list afterwards. I assume that probably you made some syntax error when replicating the list itself.

I'm going to close this

Cheers
