### ISSUE TITLE
"Acestream Can't Connect" and then "Torrent not available or invalid"

### ISSUE THREAD

**Issue by Goldensun1** [enen92/P2P-Streams-Kodi#76]
Hi,

I'm running OpenELEC 5.0.2 (x64) and Acestream won't start anymore. I've tried a couple and they count down the initial 40sec followed by the "Acestream Can't Connect" and then "Torrent not available or invalid"

OpenELEC:/ # sh $HOME/.kodi/userdata/addon_data/plugin.video.p2p-streams/acestream/start.sh
xbmc installed
.xbmc
Cannot load libraries: path /storage/.xbmc/userdata/addon_data/plugin.video.p2p-streams/acestream/lib
Traceback (most recent call last):
  File "<entry>", line 6, in <module>
  File "core.c", line 71, in
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

any idea how i can fix/correct this?

**Comment by enen92** [comment]
Remove /storage/.xbmc folder (rm -r /storage/.xbmc)
Put settings back to default in the addon settings and re-enter the addon. After that it should work.

**Comment by Goldensun1** [comment]
@enen92 Thank you  worked like a charm.

**Comment by marcsilva20** [comment]
Enen92 eu estou a utilizar ubuntu 15.04 e o kodi 15.
Instalei o plexus e ao colocar uma lista aparece-me torrent inválido.
A mim parece-me que o plexus não está a conseguir arrancar o acestream sabes como consigo corrigir isso?
Obrigado

**Comment by spike985** [comment]
Hi,
I have the same problem! I installed Kodibuntu x86 and it's working fine, i downloaded p2p stream, uploaded parsers but i get the error in the title everytime i try to open a stream with sopcast or acestream.
Do you have any suggestion?
