### ISSUE TITLE
Acestream not starting

### ISSUE THREAD

**Issue by Ankh-** [enen92/P2P-Streams-Kodi#79]
Just upgraded / installed Openelec 5.0.5 and wanted to use p2p streams, but the acestream doesn't seem to work:

> OpenELEC (official) Version: 5.0.5
> OpenELEC:~ # $HOME/.xbmc/userdata/addon_data/plugin.video.p2p-streams/acestream/acestreamengine --client-console --lib-path $HOME/.xbmc/userdata/addon_data/plugin.video.p2p-streams/acestream
> Cannot load libraries: path /storage/.xbmc/userdata/addon_data/plugin.video.p2p-streams/acestream/lib
> Traceback (most recent call last):
>   File "<entry>", line 6, in <module>
>   File "core.c", line 71, in
> ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory

Even though the directory is there:
> OpenELEC:~ # ls $HOME/.xbmc/userdata/addon_data/plugin.video.p2p-streams/acestream/lib
GeoIP-1.3.2-py2.7-linux-x86_64.egg     bitarray-0.8.1-py2.7-linux-x86_64.egg  miniupnpc-1.9-py2.7-linux-x86_64.egg   pycompat27.so
acestreamengine                        libcrypto.so.1.0.0                     psutil-1.2.1-py2.7-linux-x86_64.egg

Allready removed the directory and reinstalled, but that doesn't help. 

Sopcast works though.

**Comment by enen92** [comment]
https://github.com/enen92/P2P-Streams-Kodi/issues/76
