### ISSUE TITLE
crashes while watching

### ISSUE THREAD

**Issue by zayn008** [enen92/P2P-Streams-Kodi#86]
through a stream, about a minute in it will just close and take me back to the app, please fix this as it makes the app pretty much unusable

**Comment by enen92** [comment]
It can be either a problem with cache (configure advancedsettings.xml), the fact your brandwith is crap or problems related to acestream or the stream itself. Either the reason, it is not related with the addon code so issue closed.

**Comment by zayn008** [comment]
That's rude. I've tried with many streams and my bandwidth is fine. Works excellent on my PC. A supportive reply would've been helpful

**Comment by enen92** [comment]
It's not rude. The addon just starts the acestramengine (whice is closed source) and feeds the respective stream into xbmc. Any problems with low download rates or upload rates are independent from the addon. You didn't even mention what platform you're running the addon. You just answer now that on your pc it works fine. What is a pc? windows? Where is it causing problems...android?

**Comment by zayn008** [comment]
Sorry, it works on my windows 7 PC, I'm trying to run it on my Amazon Fire TV, the stream will open and work fine, buffer then work again then it'll stop and crash, it can't be slow speed because I have fibre optic and get around 5-8MB/s

**Comment by enen92** [comment]
Import the recomended advanced settings and port forward port 8621 on your router to your firetv ip address
