### ISSUE TITLE
Acestream crashes on rpi2

### ISSUE THREAD

**Issue by reemplazable** [enen92/P2P-Streams-Kodi#87]
There is no way to watch any Acestream in rpi2
It always crashes with:
14:21:51 T:1580200976   DEBUG: DialogProgress::StartModal called
14:21:51 T:1580200976   DEBUG: ------ Window Init (DialogProgress.xml) ------
14:21:51 T:1580200976  NOTICE: Linux not android..
14:21:55 T:1961074688   DEBUG: ------ Window Init (DialogOK.xml) ------
14:21:55 T:1961074688   DEBUG: ------ Window Init (DialogKaiToast.xml) ------
14:21:58 T:1961074688   DEBUG: Keyboard: scancode: 0x01, sym: 0x001b, unicode: 0x001b, modifier: 0x0
14:21:58 T:1961074688   DEBUG: OnKey: escape (0xf01b) pressed, action is PreviousMenu
14:21:58 T:1961074688   DEBUG: ------ Window Deinit (DialogOK.xml) ------
14:21:58 T:1580200976 WARNING: Attempt to use invalid handle -1
14:21:58 T:1580200976    INFO: CPythonInvoker(71, /home/xbian/.kodi/addons/plugin.video.p2p-streams/default.py): script successfully run
14:21:58 T:1961074688   DEBUG: ------ Window Deinit (DialogKaiToast.xml) ------
14:21:58 T:1961074688   DEBUG: ------ Window Deinit (DialogProgress.xml) ------

**Comment by enen92** [comment]
There's no acestreamengine for linux arm

**Comment by reemplazable** [comment]
:-( Read it later, sorry for the inconvenience.
