### ISSUE TITLE
How do I add an M3U list?

### ISSUE THREAD

**Issue by chovy** [enen92/P2P-Streams-Kodi#89]
I only see options for XML list or python scripts. The docs say I can add an .m3u list but it doesn't say how.

https://github.com/enen92/P2P-Streams-Kodi/wiki/Lists

**Comment by enen92** [comment]
The same way you add an .xml list. The addon checks the extension of the file and processes it accordingly.

**Comment by enen92** [comment]
If there's a problem with a specific list you can mail me the url or the list (hidding or replacing any sensitive data) and I'll check why it is not working

**Comment by chovy** [comment]
My url didn't have the proper extension.
